name: Build and Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Set global variables for test/production
      id: global-vars
      run: |
        if [[ ${{ github.ref}} = refs/heads/test ]];then
          echo ::set-output name=aws_env_prefix::dev
          echo ::set-output name=npm_build_env::test
        else
          echo ::set-output name=aws_env_prefix::prod
          echo ::set-output name=npm_build_env::prod
        fi
    - uses: actions/checkout@v1

    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

        # NOTE: This will likely need to be updated to support a production UI (npm run build:test vs npm run build)
    - name: npm install, lint, and build
      run: |
        npm install --prod
        npm run build

    - name: Deploy to s3
      env:
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY }}
      run: |
        aws s3 sync dist s3://ibdf-cloudfront-cache-test